# Base config for training poyo_plus

data_root: ./data/processed/
log_dir: ./logs

sequence_length: 1.0  # in seconds
latent_step: 0.125  # in seconds
readout_modality_name: cursor_velocity_2d

epochs: 1000
eval_epochs: 1  # frequency for doing validation 

batch_size: 128
eval_batch_size: null  # if null, will use batch_size
num_workers: 4
seed: 42

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

wandb:
  enable: true
  entity: null
  project: poyo
  run_name: null
  log_model: false

backend_config: gpu_fp32
precision: 32
nodes: 1
gpus: 1

ckpt_path: null  # for resuming training, or loading a model during finetuning

num_sanity_val_steps: 0  # only supports 0 (none) and -1 (all) right now