
- selection:
    - brainset: "allen_visual_coding_ophys_2016"
      sessions:
        - "501021421"
        - "501574836"
        - "501876401"
        - "501933264"
        - "501940850"
        - "502115959"
        - "502205092"
        - "502376461"
        - "502608215"
        - "502666254"
        - "502793808"
        - "503109347"
        - "503324629"
        - "504853580"
        - "505407318"
        - "505695962"
        - "506540916"
        - "506773185"
        - "507129766"
        - "507464107"
        - "508356957"
        - "508753256"
        - "509580400"
        - "509904120"
        - "510093797"
        - "510214538"
        - "510390912"
        - "510514474"
        - "510517131"
        - "510859641"
        - "510917254"
        - "511194579"
        - "511440894"
        - "511534603"
        - "511573879"
        - "511595995"
        - "512326618"
        - "524691284"
        - "526504941"
        - "527048992"
        - "529688779"
        - "530645663"
        - "531134090"
        - "539290504"
        - "539487468"
        - "539497234"
        - "540684467"
        - "541010698"
        - "541290571"
        - "545446482"
        - "546716391"
        - "547388708"
        - "548379748"
        - "550455111"
        - "550490398"
        - "550851591"
        - "551834174"
        - "551888519"
        - "552410386"
        - "552427971"
        - "553568031"
        - "556344224"
        - "556353209"
        - "558670888"
        - "559382012"
        - "560809202"
        - "562122508"
        - "562536153"
        - "563710064"
        - "567878987"
        - "571103671"
        - "571642389"
        - "572606382"
        - "573720508"
        - "575302108"
        - "575939366"
        - "576001843"
        - "576095926"
        - "576273468"
        - "581026088"
        - "582918858"
        - "583279803"
        - "584196534"
        - "584544569"
        - "584944065"
        - "584983136"
        - "585035184"
        - "585900296"
        - "587339481"
        - "587344053"
        - "588191926"
        - "588483711"
        - "588655112"
        - "589441079"
        - "589755795"
        - "590047029"
        - "590168385"
        - "591430494"
        - "591460070"
        - "591548033"
        - "592348507"
        - "592407200"
        - "592657427"
        - "593270603"
        - "593373156"
        - "593552712"
        - "594090967"
        - "594320795"
        - "595183197"
        - "595263154"
        - "595273803"
        - "595718342"
        - "595806300"
        - "595808594"
        - "596509886"
        - "596584192"
        - "596779487"
        - "597028938"
        - "598137246"
        - "598564173"
        - "598635821"
        - "599320182"
        - "599909878"
        - "601273921"
        - "601368107"
        - "601423209"
        - "601705404"
        - "601805379"
        - "601841437"
        - "601887677"
        - "601904502"
        - "601910964"
        - "602866800"
        - "603187982"
        - "603188560"
        - "603224878"
        - "603425659"
        - "603452291"
        - "603576132"
        - "603592541"
        - "603763073"
        - "603978471"
        - "604145810"
        - "604328043"
        - "604529230"
        - "605606109"
        - "605688822"
        - "605800963"
        - "605859367"
        - "605883133"
        - "606353987"
        - "606802468"
        - "607063420"
        - "609517556"
        - "609894681"
        - "611638995"
        - "611658482"
        - "612044635"
        - "612534310"
        - "612536911"
        - "612543999"
        - "612549085"
        - "613091721"
        - "613599811"
        - "613968705"
        - "614556106"
        - "614571626"
        - "616779893"
        - "617381605"
        - "617388117"
        - "617395455"
        - "623339221"
        - "623347352"
        - "623587006"
        - "626027944"
        - "627823636"
        - "627823695"
        - "637115675"
        - "637126541"
        - "637154333"
        - "637669270"
        - "637669284"
        - "637671554"
        - "637998955"
        - "638056634"
        - "638262558"
        - "638862121"
        - "639117196"
        - "639117826"
        - "639251932"
        - "639931541"
        - "639932847"
        - "640198011"
        - "642278925"
        - "642884591"
        - "643062797"
        - "643592303"
        - "643645390"
        - "644026238"
        - "644051974"
        - "644386884"
        - "644947716"
        - "645086975"
        - "645256361"
        - "645413759"
        - "645689073"
        - "646016204"
        - "647143225"
        - "647155122"
        - "647595665"
        - "647595671"
        - "647598519"
        - "647603932"
        - "649324898"
        - "649401936"
        - "649409874"
        - "649938038"
        - "650079244"
        - "651769499"
        - "651770186"
        - "651770380"
        - "651770794"
        - "652091264"
        - "652092676"
        - "652094901"
        - "652094917"
        - "652096183"
        - "652737678"
        - "652737867"
        - "652842495"
        - "652842572"
        - "652989442"
        - "653122667"
        - "653123929"
        - "653125130"
        - "653126877"
        - "653551965"
        - "653932505"
        - "654532828"
        - "657009581"
        - "657016267"
        - "657078119"
        - "657080632"
        - "657082055"
        - "657224241"
        - "657389972"
        - "657390171"
        - "657391037"
        - "657391625"
        - "657650110"
        - "657775947"
        - "657776356"
        - "657785850"
        - "657914280"
        - "657915168"
        - "658020691"
        - "658518486"
        - "658533763"
        - "658854537"
        - "659491419"
        - "660064796"
        - "660510593"
        - "660513003"
        - "661328410"
        - "661437140"
        - "662033243"
        - "662219852"
        - "662348804"
        - "662351164"
        - "662358771"
        - "662359728"
        - "662361096"
        - "662974315"
        - "662982346"
        - "663479824"
        - "663485329"
        - "663866413"
        - "663876406"
        - "664404274"
        - "664914611"
        - "665307545"
        - "665722301"
        - "665726618"
        - "667004159"
        - "669233895"
        - "669237515"
        - "669859475"
        - "669861524"
        - "670395725"
        - "670395999"
        - "670721589"
        - "670728674"
        - "671164733"
        - "671618887"
        - "672206735"
        - "672207947"
        - "672211004"
        - "673171528"
        - "673475020"
        - "673914981"
        - "674275260"
        - "674276329"
        - "674679019"
        - "675477919"
        - "676024666"
        - "676503588"
        - "679700458"
        - "679702884"
        - "680150733"
        - "680156911"
        - "682049099"
        - "682051855"
        - "683253712"
        - "683257169"
        - "685816006"
        - "686441799"
        - "686442556"
        - "686449092"
        - "686909240"
        - "688580172"
        - "688678766"
        - "689388034"
        - "691197571"
        - "692345003"
        - "692345336"
        - "696156783"
        - "698260532"
        - "698762886"
        - "699155265"
        - "701046700"
        - "702934964"
        - "703308071"
        - "704298735"
        - "707006626"
        - "707923645"
        - "710502981"
        - "710504563"
        - "710778377"
        - "712178483"
        - "712178511"
        - "712919665"
        - "715923832"
        - "716956096"
                - "501729039"
        - "501929610"
        - "502199136"
        - "502962794"
        - "503412730"
        - "504115289"
        - "504568756"
        - "505845219"
        - "506773892"
        - "506809539"
        - "506823562"
        - "507691036"
        - "507990552"
        - "508563988"
        - "509958730"
        - "512164988"
        - "512270518"
        - "512311673"
        - "528402271"
        - "546641574"
        - "552760671"
        - "554037270"
        - "555040116"
        - "555042467"
        - "555749369"
        - "556321897"
        - "556665481"
        - "557225279"
        - "557227804"
        - "557304694"
        - "557615965"
        - "557848210"
        - "558476282"
        - "559192380"
        - "560027980"
        - "560578599"
        - "560866155"
        - "560898462"
        - "560920977"
        - "560926639"
        - "561312435"
        - "561472633"
        - "562052595"
        - "562711440"
        - "563176332"
        - "564425777"
        - "564607188"
        - "565216523"
        - "565698388"
        - "566096665"
        - "566307038"
        - "566458505"
        - "569299884"
        - "569396924"
        - "569457162"
        - "569645690"
        - "569718097"
        - "569739027"
        - "569792817"
        - "569896493"
        - "570008444"
        - "570236381"
        - "570278597"
        - "570305847"
        - "571006300"
        - "571137446"
        - "571177441"
        - "571541565"
        - "571684733"
        - "572722662"
        - "573083539"
        - "573261515"
        - "573850303"
        - "574823092"
        - "575135986"
        - "575970700"
        - "576411246"
        - "577379202"
        - "577665023"
        - "578674360"
        - "580013262"
        - "580043440"
        - "580051759"
        - "580095647"
        - "580095655"
        - "580163817"
        - "581150104"
        - "581153070"
        - "581597734"
        - "582838758"
        - "582867147"
        - "583136567"
  config:
    multitask_readout:
      - decoder_id: DRIFTING_GRATINGS_TEMPORAL_FREQUENCY
        metrics:
          - metric: accuracy